name: jaffle_shop_mesh_finance

profile: snowflake
dbt-cloud:
  project-id: 286282

models:
  jaffle_shop_mesh_finance:
    marts:
      +materialized: table

vars:
  truncate_timespan_to: "{{ current_timestamp() }}"
  dbt_date:time_zone: America/Los_Angeles
